@ECHO OFF
cd C:/Program Files (x86)/GMAT/R2016a/bin
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/0.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/1.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/10.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/100.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/101.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/102.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/103.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/104.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/105.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/106.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/107.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/108.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/109.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/11.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/110.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/111.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/112.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/113.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/114.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/115.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/116.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/117.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/118.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/119.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/12.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/120.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/121.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/122.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/123.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/124.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/125.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/126.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/127.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/128.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/129.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/13.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/130.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/131.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/132.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/133.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/134.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/135.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/136.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/137.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/138.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/139.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/14.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/140.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/141.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/142.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/143.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/144.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/145.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/146.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/147.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/148.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/149.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/15.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/150.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/151.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/152.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/153.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/154.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/155.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/156.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/157.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/158.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/159.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/16.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/160.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/161.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/162.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/163.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/164.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/165.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/166.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/167.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/168.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/169.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/17.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/170.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/171.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/172.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/173.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/174.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/175.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/176.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/177.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/178.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/179.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/18.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/180.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/181.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/182.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/183.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/184.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/185.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/186.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/187.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/188.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/189.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/19.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/190.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/191.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/192.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/193.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/194.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/195.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/196.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/197.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/198.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/199.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/2.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/20.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/200.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/201.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/202.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/203.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/204.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/205.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/206.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/207.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/208.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/209.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/21.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/210.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/211.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/212.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/213.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/214.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/215.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/216.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/217.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/218.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/219.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/22.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/220.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/221.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/222.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/223.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/224.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/225.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/226.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/227.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/228.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/229.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/23.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/230.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/231.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/232.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/233.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/234.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/235.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/236.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/237.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/238.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/239.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/24.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/240.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/241.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/242.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/243.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/244.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/245.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/246.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/247.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/248.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/249.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/25.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/250.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/251.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/252.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/253.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/254.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/255.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/256.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/257.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/258.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/259.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/26.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/260.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/261.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/262.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/263.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/264.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/265.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/266.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/267.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/268.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/269.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/27.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/270.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/271.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/272.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/273.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/274.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/275.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/276.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/277.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/278.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/279.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/28.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/280.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/281.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/282.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/283.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/284.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/285.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/286.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/287.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/288.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/289.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/29.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/290.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/291.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/292.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/293.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/294.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/295.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/296.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/297.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/298.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/299.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/3.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/30.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/300.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/301.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/302.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/303.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/304.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/305.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/306.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/307.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/308.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/309.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/31.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/310.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/311.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/312.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/313.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/314.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/315.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/316.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/317.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/318.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/319.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/32.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/320.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/321.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/322.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/323.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/324.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/325.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/326.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/327.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/328.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/329.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/33.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/330.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/331.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/332.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/333.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/334.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/335.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/336.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/337.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/338.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/339.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/34.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/340.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/341.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/342.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/343.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/344.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/345.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/346.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/347.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/348.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/349.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/35.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/350.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/351.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/352.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/353.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/354.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/355.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/356.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/357.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/358.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/359.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/36.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/360.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/361.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/362.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/363.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/364.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/365.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/366.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/367.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/368.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/369.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/37.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/370.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/371.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/372.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/373.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/374.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/375.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/376.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/377.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/378.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/379.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/38.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/380.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/381.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/382.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/383.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/384.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/385.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/386.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/387.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/388.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/389.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/39.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/390.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/391.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/392.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/393.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/394.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/395.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/396.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/397.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/398.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/399.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/4.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/40.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/400.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/401.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/402.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/403.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/404.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/405.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/406.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/407.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/408.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/409.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/41.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/410.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/411.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/412.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/413.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/414.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/415.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/416.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/417.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/418.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/419.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/42.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/420.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/421.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/422.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/423.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/424.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/425.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/426.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/427.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/428.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/429.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/43.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/430.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/431.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/432.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/433.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/434.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/435.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/436.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/437.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/438.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/439.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/44.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/440.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/441.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/442.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/443.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/444.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/445.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/446.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/447.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/448.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/449.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/45.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/450.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/451.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/452.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/453.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/454.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/455.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/456.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/457.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/458.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/459.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/46.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/460.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/461.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/462.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/463.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/464.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/465.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/466.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/467.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/468.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/469.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/47.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/470.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/471.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/472.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/473.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/474.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/475.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/476.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/477.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/478.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/479.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/48.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/480.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/481.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/482.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/483.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/484.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/485.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/486.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/487.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/488.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/489.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/49.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/490.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/491.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/492.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/493.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/494.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/495.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/496.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/497.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/498.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/499.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/5.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/50.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/500.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/501.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/502.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/503.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/504.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/505.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/506.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/507.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/508.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/509.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/51.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/510.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/511.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/512.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/513.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/514.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/515.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/516.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/517.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/518.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/519.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/52.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/520.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/521.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/522.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/523.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/524.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/525.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/526.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/527.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/528.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/529.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/53.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/530.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/531.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/532.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/533.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/534.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/535.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/536.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/537.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/538.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/539.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/54.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/540.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/541.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/542.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/543.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/544.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/545.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/546.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/547.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/548.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/549.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/55.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/550.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/551.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/552.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/553.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/554.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/555.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/556.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/557.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/558.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/559.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/56.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/560.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/561.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/562.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/563.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/564.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/565.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/566.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/567.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/568.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/569.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/57.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/570.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/571.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/572.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/573.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/574.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/575.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/576.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/577.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/578.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/579.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/58.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/580.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/581.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/582.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/583.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/584.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/585.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/586.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/587.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/588.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/589.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/59.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/590.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/591.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/592.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/593.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/594.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/595.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/596.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/597.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/598.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/599.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/6.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/60.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/600.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/601.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/602.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/603.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/604.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/605.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/606.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/607.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/608.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/609.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/61.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/610.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/611.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/612.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/613.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/614.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/615.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/616.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/617.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/618.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/619.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/62.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/620.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/621.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/622.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/623.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/624.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/625.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/626.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/627.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/628.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/629.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/63.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/630.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/631.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/632.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/633.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/634.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/635.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/636.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/637.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/638.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/639.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/64.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/640.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/641.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/642.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/643.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/644.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/645.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/646.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/647.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/648.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/649.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/65.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/650.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/651.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/652.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/653.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/66.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/67.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/68.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/69.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/7.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/70.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/71.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/72.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/73.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/74.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/75.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/76.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/77.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/78.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/79.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/8.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/80.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/81.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/82.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/83.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/84.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/85.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/86.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/87.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/88.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/89.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/9.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/90.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/91.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/92.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/93.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/94.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/95.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/96.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/97.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/98.script
GMAT.exe -r -x -m C:/Users/mattg/Documents/GitHub/GMAT-automation/Generated-Scripts/99.script
